<?php

$_COS_LANG_MODULE['Log in in order to follow this post'] = 'Log ind for at følge dette indlæg';
$_COS_LANG_MODULE['Follow'] = 'Følg';
$_COS_LANG_MODULE['Log in to follow'] = 'Log ind for at følge';
$_COS_LANG_MODULE['Click to follow'] = 'Klik for at følge';
$_COS_LANG_MODULE['Click to stop following'] = 'Klik for at stoppe efter';
$_COS_LANG_MODULE['Click to unfollow'] = 'Klik for at unfollow';
