<?php


// Translation of file /modules/follow/module.php

$_COS_LANG_MODULE['Log in in order to follow this post'] = 'Log in in order to follow this post';
$_COS_LANG_MODULE['Follow'] = 'Follow';
$_COS_LANG_MODULE['Log in to follow'] = 'Log in to follow';
$_COS_LANG_MODULE['Click to follow'] = 'Click to follow';
$_COS_LANG_MODULE['Click to stop following'] = 'Click to stop following';
$_COS_LANG_MODULE['Click to unfollow'] = 'Click to unfollow';
