<?php

$_COS_LANG_MODULE['Log in in order to follow this post'] = 'Logg inn for å følge dette innlegget';
$_COS_LANG_MODULE['Follow'] = 'Følg';
$_COS_LANG_MODULE['Log in to follow'] = 'Logg inn for å følge';
$_COS_LANG_MODULE['Click to follow'] = 'Klikk for å følge';
$_COS_LANG_MODULE['Click to stop following'] = 'Klikk for å slutte å følge';
$_COS_LANG_MODULE['Click to unfollow'] = 'Klikk for å unfollow';
