<?php

$_COS_LANG_MODULE['Log in in order to follow this post'] = 'Kirjaudu sisään seurata viestistä';
$_COS_LANG_MODULE['Follow'] = 'Seurata';
$_COS_LANG_MODULE['Log in to follow'] = 'Kirjaudu sisään seurata';
$_COS_LANG_MODULE['Click to follow'] = 'Klikkaa seurata';
$_COS_LANG_MODULE['Click to stop following'] = 'Klikkaa lopettaa seuraavat';
$_COS_LANG_MODULE['Click to unfollow'] = 'Klikkaa unfollow';
