<?php

$_COS_LANG_MODULE['You need to log in if you want to follow'] = 'Du måste logga in om du vill följa';
$_COS_LANG_MODULE['Log in in order to follow this post'] = 'Logga in för att följa detta inlägg';
$_COS_LANG_MODULE['Follow'] = 'Följ';
$_COS_LANG_MODULE['Log in to follow'] = 'Logga in för att följa';
$_COS_LANG_MODULE['Click to follow'] = 'Klicka för att följa';
$_COS_LANG_MODULE['Click to stop following'] = 'Klicka för att sluta följa';
$_COS_LANG_MODULE['Click to unfollow'] = 'Klicka för att sluta följa';
